name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Flutter pub get
        run: flutter pub get
        
      - name: Build APK (release)
        run: flutter build apk --release --split-per-abi --android-skip-build-dependency-validation
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: adhkar-app-release-apk
          path: |
            build/app/outputs/flutter-apk/app-*-release.apk
